# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end


 lane :sync_certificates do
   match({readonly: true, type: "appstore"})
 end

 lane :build do
   sync_certificates
   increment_build_number
   gym
 end

 lane :beta do
   build
   pilot  
 end


app_store_connect_api_key(
   key_id: "FY54F3KNKW",
   issuer_id: "084cb549-2d0b-4b86-8008-1047ab432d66",
   key_content: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ0h5ekZOa2F5YnBCUFJaWVEKUldqN2M4eTJtZFVlTjB5VXU3dGVNUDNEOGtLZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTK1lxaE9qZ1NOY1BJYgpjZmRsZG5PUlFHSDZPTmo4UEhlajhhNUdmSUxsaFRLU0J0SWpza09FQldkclJyWGFOZFRGQWN1V3FYWDhrbjRNCjlZTFBkdlVJCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
   is_key_content_base64: true,
   in_house: false
 )
